kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipelines-scc-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "get", "list", "delete"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: signing
  labels:
    # operator.tekton.dev/operand-name: tektoncd-pipelines
    operator.tekton.dev/operand-name: tektonpipelines
subjects:
- kind: ServiceAccount
  name: pipeline-signing
  namespace: tektest
roleRef:
  kind: ClusterRole
  name: pipelines-scc-role
  apiGroup: rbac.authorization.k8s.io
