apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  labels:
    tekton.dev/pipeline: image-build
  name: image-build-demo-2
  namespace: tektest
spec:
  pipelineRef:
    name: image-build
  serviceAccountName: pipeline-signing
  timeout: 1h0m0s
  workspaces:
  - name: build
    persistentVolumeClaim:
        claimName: tektonpvc
