apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: clone-build-push-run-
  namespace: tektest
spec:
  pipelineRef:
    name: clone-build-push
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
    - name: shared-data
      persistentVolumeClaim:
        claimName: tektonpvc
    - name: docker-credentials
      secret:
        secretName: docker-credentials
  params:
    - name: url
      value: "https://github.com/CloudMasonPods/SecuritySprint01-Pod1.git"
    - name: image-reference
      value: docker.io/moyu597/ethereum/eth:latest