apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: harbor
    meta.helm.sh/release-namespace: harbor
  creationTimestamp: "2024-03-17T13:54:00Z"
  labels:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: 7.2.4
    helm.sh/chart: redis-18.19.2
  name: harbor-redis-master
  namespace: harbor
  resourceVersion: "8610847"
  uid: d3c1a24a-b1e1-44b8-ab9d-e2ae392c949b
spec:
  clusterIP: 10.43.22.58
  clusterIPs:
  - 10.43.22.58
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-redis
    port: 6379
    protocol: TCP
    targetPort: redis
  selector:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/name: redis
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
