# apiVersion: tekton.dev/v1beta1
# kind: Task
# metadata:
#   name: build-dockerfile
#   namespace: tekton-cicd
# spec:
#   params:
#     - name: image-name
#       type: string
#       description: The name of the image to build
#   workspaces:
#     - name: source-build-workspace-2
#       description: The workspace containing the cloned Git repository for building
#   steps:
#     - name: build
#       image: gcr.io/kaniko-project/executor:latest
#       env:
#         - name: DOCKER_CONFIG
#           value: /kaniko/.docker
#       command:
#         - /kaniko/executor
#         - --dockerfile=/workspace/source-build-workspace-2/repo/Dockerfile
#         - --context=/workspace/source-build-workspace-2
#         - --destination=$(params.image-name)
#         - --no-push
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push-dockerfile
  namespace: tekton-cicd
spec:
  params:
    - name: image-name
      type: string
      description: The name of the image to build and push
    - name: registry-url
      type: string
      description: The URL of the private Harbor registry
  workspaces:
    - name: source
      description: The workspace containing the cloned Git repository for building
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      env:
        - name: DOCKER_CONFIG
          value: /kaniko/.docker
      command:
        - /kaniko/executor
        - --insecure
        - --skip-tls-verify
        - --dockerfile=/workspace/source/repo/Dockerfile
        - --context=/workspace/source
        - --destination=$(params.registry-url)/$(params.image-name)
      volumeMounts:
        - name: config-json #mount the volume i.e the name of the secrte to kaniko
          mountPath: /kaniko/.docker
  volumes:
    - name: config-json
      secret:
        secretName: config-json
        defaultMode: 256
        