#used to check content in workspace
apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: tekton-cicd
spec:
  containers:
  - name: debug-container
    image: alpine:latest
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600"]
    volumeMounts:
    - mountPath: /workspace/shared-data
      name: shared-data  # Corrected volume name
  restartPolicy: Never
  volumes:
  - name: shared-data  # Corrected volume name
    persistentVolumeClaim:
      claimName: tektonpvc  # Ensure correct PVC name

