# pipelinerun-git-clone.yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: git-clone-pipeline-run
  namespace: tekton-cicd
spec:
  pipelineRef:
    name: git-clone-pipeline
  params:
  - name: git-url
    value: "https://github.com/CloudMasonPods/SecuritySprint01-Pod1.git"
  - name: git-revision
    value: main #if the git-revision is left blank the default from the task would then 
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi