apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: git-clone-pipeline
  namespace: tekton-cicd
spec:
  params:
    - name: git-url
      type: string
    - name: git-revision
      type: string
      default: main
    - name: image-name
      type: string
      description: The name of the image to build and push
    - name: registry-url
      type: string
      description: The URL of the private Harbor registry
  workspaces:
    - name: shared-data
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: source
          workspace: shared-data
    - name: check-dockerfile
      taskRef:
        name: check-dockerfile
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-data
    - name: build-and-push-dockerfile
      taskRef:
        name: build-and-push-dockerfile
      runAfter:
        - check-dockerfile
      params:
        - name: image-name
          value: $(params.image-name)
        - name: registry-url
          value: $(params.registry-url)
        - name: TAG
          value: $(tasks.fetch-repository.results.commit)
      workspaces:
        - name: source
          workspace: shared-data
      