apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pull-github-webhook-template
  namespace: tekton-triggers
spec:
  params:
    - name: pr-number
      description: Pull request number
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        generateName: pr-pipeline-run-
      spec:
        pipelineRef:
          name: your-pr-pipeline # Replace with your pull request pipeline name
        params:
          - name: pr-number
            value: $(tt.params.pr-number)
