apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: push-github-webhook-binding
  namespace: tekton-triggers
spec:
  params:
    - name: git-url
      value: $(body.repository.clone_url)
    - name: git-revision
      value: $(body.after)