apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-triggers-binding
  namespace: tekton-cicd # Replace with your namespace
subjects:
  - kind: ServiceAccount
    name: tekton-triggers
    namespace: tekton-cicd # Replace with your namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-clusterrole