apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ethapp
  namespace: argocd
spec:
  destination:
    namespace: eth #namespace to monitor 
    server: 'https://kubernetes.default.svc'
  source:
    path: ethereum-deployment/ethereum-subchart # Specify the required path to track in this case the folder with subchart and ingress
    repoURL: 'https://github.com/CloudMasonPods/SecuritySprint01-Pod1.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true # Automatically create namespace if it doesn't exist
