apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers-eth
  namespace: tekton-cicd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: triggers-eth-eventlistener-binding
subjects:
  - kind: ServiceAccount
    name: tekton-triggers-eth
    namespace: tekton-cicd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: triggers-eth-eventlistener-clusterbinding
subjects:
  - kind: ServiceAccount
    name: tekton-triggers-eth
    namespace: tekton-cicd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles