apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ethereum
  namespace: ethereum-deployment
spec:
  secretName: ethereum-secret
  issuerRef:
    name: acme-issuer
    # kind: Issuer
    # - or -
    kind: ClusterIssuer
  dnsNames:
    - 'ethereum.gm-nig-ltd.tech'